---
- name: Ensure clickhouse config, data and logs exist
  file:
    dest: "{{ item }}"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    state: directory
  with_items:
    - "{{ clickhouse_path_config }}"
    - "{{ clickhouse_path_config_d }}"
    - "{{ clickhouse_path_log }}"
    - "{{ clickhouse_path_tmp }}"
    - "{{ clickhouse_path_data }}"

  notify: restart-ch

- name: Config system
  template:
    src: config.xml.j2
    dest: "{{ clickhouse_path_config }}/config.xml"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  notify: restart-ch

# user conf does not force to restart :)
- name: Config users
  template:
    src: users.xml.j2
    dest: /etc/clickhouse-server/users.d/{{ item.user_name }}.xml
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  with_items: "{{ clickhouse_user_list }}"
  no_log: true

- name: Config remote_servers
  template:
    src: remote_servers.xml.j2
    dest: "{{ clickhouse_path_config_d }}/clickhouse_remote_servers.xml"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  notify: restart-ch

- name: Config macros 
  template:
    src: macros.xml.j2
    dest: "{{ clickhouse_path_config_d }}/macros.xml"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    mode: 0644
  notify: restart-ch
  