---

- name: Converge Zookeeper
  hosts: zookeeper
  tasks:
    - name: "Include java role for zookeeper"
      include_role:
        name: "java"

    - name: "Include ansible-role-zookeeper"
      include_role:
        name: "zookeeper"

- name: Converge Clickhouse
  hosts: clickhouse
  tasks:
    - name: "Include ansible-role-clickhouse"
      include_role:
        name: "ansible-role-clickhouse"
