---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check ClickHouse service status
      command: systemctl status clickhouse-server
      args:
        warn: no
      register: service_status
      changed_when: no
      ignore_errors: yes

    - name: Verify ClickHouse is running
      assert:
        that:
          - "'Active: active (running)' in service_status.stdout"